### ISSUE TITLE
Nice features

### ISSUE THREAD

**Issue by ultr4nerd** [Zack-Dx/Mini-TODO#1]
Hey! Can I add some features?

**Comment by Zack-Dx** [comment]
@ultr4nerd sure welcome.

**Comment by lysnbrl** [comment]
Hi, can I also help adding other features?

**Comment by Zack-Dx** [comment]
@lysnbrl Sure.

**Comment by divyang9575** [comment]
I can add some features.

**Comment by Zack-Dx** [comment]
> I can add some features.
Sure.

**Comment by prabhleenn** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if you assign me this.
