### ISSUE TITLE
Head Text and UI

### ISSUE THREAD

**Issue by anubhav2102** [Zack-Dx/Mini-TODO#10]
I would like to add head text like that in mobile view(Blueberry KEEP), also like to apply same background color and UI same as in mobile view.
Can i work on this? Please also add the hacktober label. Thanks!

**Comment by Zack-Dx** [comment]
> I would like to add head text like that in mobile view(Blueberry KEEP), also like to apply same background color and UI same as in mobile view. Can i work on this? Please also add the hacktober label. Thanks!

@anubhav2102 Hi Anubhav yea you can!
