### ISSUE TITLE
fix footer padding

### ISSUE THREAD

**Issue by Huper12345** [Zack-Dx/Mini-TODO#106]
if it is necessary to solve the occurrence of a retreat in the footer, I will be happy to fix this

![footer](https://user-images.githubusercontent.com/115031997/198844619-452b4b1d-fdc4-42b5-98cf-db7190f403a0.jpg)

@Zack-Dx

**Comment by Zack-Dx** [comment]
> if it is necessary to solve the occurrence of a retreat in the footer, I will be happy to fix this
> 
> ![footer](https://user-images.githubusercontent.com/115031997/198844619-452b4b1d-fdc4-42b5-98cf-db7190f403a0.jpg)
> 
> @Zack-Dx

Sure.
