### ISSUE TITLE
Upgrade note color

### ISSUE THREAD

**Issue by Huper12345** [Zack-Dx/Mini-TODO#107]
Now, with successful or unsuccessful creation of notes, notifications of the same color, the same when editing. I propose to fix this.
![2](https://user-images.githubusercontent.com/115031997/198845689-b44ac234-54d0-4022-bb4c-eab01593c124.png)

![3](https://user-images.githubusercontent.com/115031997/198845704-418a4e61-7efd-4229-aab1-060cfe73dfc1.png)
@Zack-Dx

**Comment by Zack-Dx** [comment]
@Huper12345 they are not same for now. Update your forked branch.

**Comment by Huper12345** [comment]
@Zack-Dx 

Updated fork branch. The color of notifications is the same, maybe you misunderstood me). I want to make them different so that the user understands better what is happening.

For example
Before-------------------------
![before](https://user-images.githubusercontent.com/115031997/198896584-dc9ad1dd-3ba9-44bc-b5a1-1618fdaf4e02.jpg)
![before2](https://user-images.githubusercontent.com/115031997/198896585-3676a025-6916-4661-b67d-c3e8dc14a3f6.jpg)
![before3](https://user-images.githubusercontent.com/115031997/198896588-5604fa68-ef7c-45dc-8364-db1cb56737e7.jpg)

After ----------------------
![after](https://user-images.githubusercontent.com/115031997/198896604-d28ac9af-2763-4427-8549-b4aac7c51ac8.jpg)
![after2](https://user-images.githubusercontent.com/115031997/198896606-49845877-6a8b-4466-98d1-0635cf126063.jpg)
![after3](https://user-images.githubusercontent.com/115031997/198896610-51b10762-8930-44dc-b500-4393c027a55f.jpg)
