### ISSUE TITLE
Add links to icons

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Zack-Dx/Mini-TODO#112]
![image](https://user-images.githubusercontent.com/78332454/198849994-4ce18124-8e47-4b68-aab1-8dbdd689585a.png)
pls assign me this issue

**Comment by nishtha53** [comment]
can i work on this issue?

**Comment by AnshuPathak-88825** [comment]
Sorry I've already asked before you so you can another issue

**Comment by nishtha53** [comment]
@AnshuPathak-88825 yes sure.

**Comment by Zack-Dx** [comment]
> ![image](https://user-images.githubusercontent.com/78332454/198849994-4ce18124-8e47-4b68-aab1-8dbdd689585a.png) pls assign me this issue

which icons the one in the footer?

**Comment by AnshuPathak-88825** [comment]
all social links

**Comment by Zack-Dx** [comment]
> all social links

I think the ones required are already linked to their respective platform.

**Comment by talib1996** [comment]
only the link to github is set. you should provide links o all other social media platforms(linkedin, instagram, twitter), so that it would point to the exact social media platform.
Can you assign me this task ?
