### ISSUE TITLE
Change logo to match the theme

### ISSUE THREAD

**Issue by michelle-santiago** [Zack-Dx/Mini-TODO#117]
I would like to add new logo for favicon.io and header title using font awesome for hacktoberfest to match the color theme. Please assign me tyy

**Comment by michelle-santiago** [comment]
#118 https://github.com/Zack-Dx/Mini-TODO/pull/118

**Comment by michelle-santiago** [comment]
#119

**Comment by Zack-Dx** [comment]
> I would like to add new logo for favicon.io and header title using font awesome for hacktoberfest to match the color theme. Please assign me tyy

Sure mate.
