### ISSUE TITLE
Site file structure

### ISSUE THREAD

**Issue by AlexJaneMercer** [Zack-Dx/Mini-TODO#121]
Hey Zack!
I would like to edit the file structure of the site so as not to get lost in the files. 
![image](https://user-images.githubusercontent.com/102369284/198872996-d41d3ece-2849-462e-891e-fada42fd6a80.png)
![image](https://user-images.githubusercontent.com/102369284/198873004-12b116af-5631-41a2-adaa-3a70f326dd6b.png)

**Comment by Zack-Dx** [comment]
@AlexJaneMercer ya sure make sure they are properly linked to each other.

**Comment by AlexJaneMercer** [comment]
already
