### ISSUE TITLE
Edit Functionality is not working

### ISSUE THREAD

**Issue by syedjafer** [Zack-Dx/Mini-TODO#17]

**Comment by theGeekyLad** [comment]
Could you assign this to me, please?

**Comment by Zack-Dx** [comment]
@theGeekyLad done.

**Comment by syedjafer** [comment]
@theGeekyLad Edit functionality is taking the value from `#note` input value. Maybe we need to shift the logic from note id input to the individual forms

**Comment by divyang9575** [comment]
Could you assign this task to me sir?

**Comment by Zack-Dx** [comment]
> @theGeekyLad Edit functionality is taking the value from `#note` input value. Maybe we need to shift the logic from note id input to the individual forms

@Exactly.

**Comment by Zack-Dx** [comment]
> Could you assign this task to me sir?

Sure.

**Comment by singhkaran202** [comment]
I'd love to work on this if that's OK. @Zack-Dx, Could you please assign me this issue?

**Comment by singhkaran202** [comment]
Thanks @Zack-Dx !!

**Comment by theGeekyLad** [comment]
There's a PR that fixes this issue enabling in-situ edits on a note. Here's what it looks like and above is the PR:

![mini-todo](https://user-images.githubusercontent.com/15625446/198126959-62236be5-3a0c-456f-b38b-7e9c4bde9e8a.gif)
