### ISSUE TITLE
Change the Edit  Note message!

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Mini-TODO#41]
Change the Edit Note message as the functionality has been updated.

**Comment by devilkiller-ag** [comment]
Can I work on this?

**Comment by Zack-Dx** [comment]
> Can I work on this?

Sure.

**Comment by devilkiller-ag** [comment]
Can you please elaborate what the new message should be?

**Comment by Zack-Dx** [comment]
> Can you please elaborate what the new message should be?

You can remove the message too. We don't need it anymore.

**Comment by devilkiller-ag** [comment]
![image](https://user-images.githubusercontent.com/43639341/198193824-18116a0c-40c9-4b24-a362-11d465f240cb.png)

**Comment by devilkiller-ag** [comment]
Will this be okay? Or should I remove it completely?

**Comment by Zack-Dx** [comment]
> Will this be okay? Or should I remove it completely?

Remove it, I think it'll look clean.

**Comment by devilkiller-ag** [comment]
> > Will this be okay? Or should I remove it completely?
> 
> Remove it, I think it'll look clean.

Sure

**Comment by devilkiller-ag** [comment]
Kindly check the changes.
![image](https://user-images.githubusercontent.com/43639341/198197562-585c3efa-d1bb-4691-81f2-660cf028055d.png)
