### ISSUE TITLE
Enhancement in UI💜

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Mini-TODO#48]

**Comment by PawanPatil19** [comment]
Can you assign me this?

**Comment by divyang9575** [comment]
Please assign this to me.

**Comment by Zack-Dx** [comment]
@PawanPatil19 @divyang9575 @prabhleenn I'm assigning this to you all as I don't want to waste someone's effort. I'll happily merge your prs just try to communicate with each other just to tell which part u're working on thanks!

**Comment by khanhtranngoccva** [comment]
Hey, I would like to be assigned this issue as well.

**Comment by prabhleenn** [comment]
@Zack-Dx can you please provide description for the work assigned work? thankyou!

**Comment by Zack-Dx** [comment]
> @Zack-Dx can you please provide description for the work assigned work? thankyou!

Just any sort of interactive UI changes would do.

**Comment by RiyaBhaskar12** [comment]
Hey! Please assign me thus issue.

**Comment by Zack-Dx** [comment]
> Hey! Please assign me thus issue.

Sure.

**Comment by Ajay1105** [comment]
Hello! Assign this issue to me

**Comment by RiyaBhaskar12** [comment]
@Zack-Dx  I've added a new color theme . plz check.

**Comment by Huper12345** [comment]
Please assign this to me
