### ISSUE TITLE
Adding a background 

### ISSUE THREAD

**Issue by kushaljgec2025** [Zack-Dx/Mini-TODO#76]
I think a good background image is necessary for making attractive the website.

**Comment by kushaljgec2025** [comment]
I am working on that please assign me

**Comment by Zack-Dx** [comment]
Make sure it relates with the theme.

**Comment by SaxenaAnushka102** [comment]
Hello @Zack-Dx ! I'd like to contribute. Is there any design I can create for the project?

**Comment by Zack-Dx** [comment]
> Hello @Zack-Dx ! I'd like to contribute. Is there any design I can create for the project?

Ya why not! just make sure it's unique and goes with the theme.
