### ISSUE TITLE
Make it responsive.

### ISSUE THREAD

**Issue by divyang9575** [Zack-Dx/Mini-TODO#79]
I can work on this issue.

**Comment by ashwini099** [comment]
i can contribute to make it more responsive

**Comment by ashwini099** [comment]
#added to-do header as a link and icon which is in navbar to redirect directly to the list which have been created and if list get bigger then we can directly go to the list and do our work.

**Comment by Zack-Dx** [comment]
@divyang9575 @ashwini099 Sure.

**Comment by tophermoa** [comment]
Hello. Can i work on this?

I think the whole UI could be more responsive in some elements.
![responsive merge](https://user-images.githubusercontent.com/32489323/198870558-eb3c9164-ac08-4d91-b702-5406559eb058.PNG)
