### ISSUE TITLE
Putting repeated code into a function

### ISSUE THREAD

**Issue by B0r1Koff** [Zack-Dx/Mini-TODO#94]
![Screenshot_20221029-172300](https://user-images.githubusercontent.com/90470009/198836748-64fc4a52-20bb-459c-a325-ba2ccdaeee64.jpg)
Hello, @Zack-Dx! There is a duplication of code in the 'index.js' file, I want to put it in a separate function

**Comment by Tubaleviao** [comment]
I sent a PR! I guess this code solve the issue. I tested it in my machine and it's working properly, let me know if you want anything different!
