### ISSUE TITLE
Automatically update copywrite year

### ISSUE THREAD

**Issue by kalosFestus** [Zack-Dx/Mini-TODO#95]
Hello @Zack-Dx , I feel the code to update the copyright year can be included to avoid having to manually do this from the code base in subsequent years, I could work on it if approved and assigned, thank you

Screenshots

**Comment by Zack-Dx** [comment]
@kalosFestus sure

**Comment by kalosFestus** [comment]
Hi @Zack-Dx,  I have added code to update the copyright year, thank you.
